- name: Load HA-Bridge settings for ARMv7 systems
  ansible.builtin.include_vars:
    file: armv7.yml
  when: ansible_architecture == 'armv7l'

- name: Create HA-Bridge folder structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ ha_bridge_path }}"

- name: Create HA-Bridge startup script
  ansible.builtin.template:
    src: docker.ha-bridge.service.j2
    dest: /etc/systemd/system/docker.ha-bridge.service
    owner: root
    group: root
    mode: 0644
  notify: Restart HA-Bridge service

- name: Force all notified handlers to run at this point
  ansible.builtin.meta: flush_handlers

- name: Start HA-Bridge service
  ansible.builtin.systemd:
    name: docker.ha-bridge
    state: started
    daemon_reload: true

- name: Wait for HA-Bridge service startup
  ansible.builtin.uri:
    url: "http://localhost:{{ ha_bridge_http_port }}/"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
