- name: Load HA-Bridge settings for ARMv7 systems
  include_vars:
    file: armv7.yml
  when: ansible_architecture == 'armv7l'
  tags:
    - ha-bridge

- name: Create HA-Bridge folder structure
  file:
    path: "{{item}}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ha_bridge_path}}"
  tags:
    - ha-bridge

- name: Create HA-Bridge startup script
  template:
    src: docker.ha-bridge.service.j2
    dest: /etc/systemd/system/docker.ha-bridge.service
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload Systemd daemon
    - Restart HA-Bridge service
  tags:
    - ha-bridge

- name: Force all notified handlers to run at this point
  meta: flush_handlers

- name: Start HA-Bridge service
  service:
    name: docker.ha-bridge
    state: started
    enabled: yes
  tags:
    - ha-bridge

- name: Wait for HA-Bridge service startup
  uri:
    url: "http://localhost:{{ha_bridge_http_port}}/"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
  tags:
    - ha-bridge
